name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 4fe53529311ebcb61f8b41aecb79304619c7cfac

    - name: Build HandBrake Linux
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake ..
        make
